DISCRIMINATOR:
  filters_disc: 128
  learning_rate_disc: 1e-5
EVAL:
  add_postprocessing_noise: true
  avg_pooling: true
  max_pooling: true
  num_batches: 25
  postprocessing_noise_factor: 1e-3
GENERAL:
  mode: GAN
  problem_type: normal
GENERATOR:
  filters_gen: 32
  latent_variables: 50
  learning_rate_gen: 1e-5
  noise_channels: 4
MODEL:
  architecture: forceconv
  padding: reflect
SETUP:
  log_folder: /home/c/cooperf/data/cGAN/ICPAC/24h_IMERG_v7_30h-54h_mk4/lead_day/logs_5
TRAIN:
  CL_type: ensmeanMSE
  batch_size: 4
  content_loss_weight: 1000.0
  ensemble_size: 8
  kl_weight: 1e-8
  num_samples: 204800
  steps_per_checkpoint: 128
  train_years:
  - 2018
  - 2019
  - 2020
  - 2021
  training_weights:
  - 0.4
  - 0.3
  - 0.2
  - 0.1
VAL:
  val_size: 8
  val_years: 2020
